language: android
android:
   components:
      - platform-tools
      - android-21
      - build-tools-21.1.0
      - extra
jdk: oraclejdk8
notifications:
    email: false
sudo: false

script:
   - rake
